import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { GlobalProvider } from "@/components/GlobalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="w-full h-48 ">
        
      <GlobalProvider>
        {children} </GlobalProvider>
      </div>
      </body>
    </html>
  );
}
